apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: limited-binding
  namespace: rbac-test

subjects:
- kind: User
  name: limiteduser
  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: limited-role
  apiGroup: rbac.authorization.k8s.io