apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: limited-role-dev
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list"]
- apiGroups: ["apps", "batch", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["list"]
