apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: limited-binding-dev
  namespace: dev

subjects:
- kind: ServiceAccount
  name: limiteduser
  namespace: default

roleRef:
  kind: Role
  name: limited-role-dev
  apiGroup: rbac.authorization.k8s.io