apiVersion: v1
kind: Pod
metadata:
  name: my-single-pod
  namespace: dev
spec:
  containers:
  - name: my-image-alpine-sleep
    image: alpine:3.20.1
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;"]