apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-ns-reader-binding
  namespace: rbac-test

subjects:
- kind: ServiceAccount
  name: user1
  namespace: rbac-test
#  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: ns-reader
  apiGroup: rbac.authorization.k8s.io