apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding

subjects:
  - kind: User
    name: cluster-admin-user
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: ClusterRole
  name: my-cluster-admin
  apiGroup: rbac.authorization.k8s.io