kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: all-read
subjects:
- kind: ServiceAccount
  name: limiteduser
  namespace: default
roleRef:
  kind: ClusterRole
  name: all-reader
  apiGroup: rbac.authorization.k8s.io
