apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-reader
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list"]

- apiGroups: ["apps", "networking.k8s.io", "rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["list"]

- apiGroups: [""]
  resources: ["nodes/proxy", "pods/log"]
  verbs: ["get"]

- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]

- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["list", "get"]

- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","delete", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create"]